sonata_translation:
    locales: [en, pl, ru, de, fr, pt_BR]
    default_locale: en
    # here enable the types you need
    gedmo:
        enabled: true
    #knplabs:
    #    enabled: true
    #phpcr:
    #    enabled: true
