doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataClassificationBundle: ~
                    ApplicationSonataClassificationBundle:
                        type: annotation

sonata_classification:
